### ISSUE TITLE
Torrent list not yet available. Connection to rtorrent not established.

### ISSUE THREAD

**Issue by psycholyzern** [dannyti/sboxsetup#11]
I have checked with command ```ps aux | grep rtorrent``` and rtorrent is running.
But still rutorrent gave me error. Im clueless.

**Comment by dannyti** [comment]
Are you sorted yet ?

**Comment by psycholyzern** [comment]
Sorry for the late reply. The script success on 3rd OS reinstall. I don't know why it doesnt work on the first 2 tries.
