### ISSUE TITLE
SickRage not working.

### ISSUE THREAD

**Issue by Switouney** [dannyti/sboxsetup#12]
Hello dannyti, thx for ur script.

my sickrage is working after installation but i can't download. i have try to restart the service but i can't relaunch :(

error:  http://pastebin.com/KQh4yei1

thanks :-)

**Comment by dannyti** [comment]
What I gather is that Sickragetv is working but you cant download from your sources. A reboot wont be of much help since its a config issue, more specific to Sickragetv forums.

Anyhow, go ahead and Try rebooting.

**Comment by Switouney** [comment]
hello, 

no, after a "service sickrage restart" i can't re-launch the service...

Jan 05 00:00:18 sd-88161 systemd[1]: Unit sickrage.service entered failed state.
Jan 05 00:00:22 sd-88161 sickrage[9658]: Starting SickBeard:PID file: /var/run/s
Jan 05 00:00:22 sd-88161 sickrage[9658]: failed!
Jan 05 00:00:22 sd-88161 systemd[1]: sickrage.service: control process exited, c
Jan 05 00:00:22 sd-88161 systemd[1]: Failed to start LSB: starts instance of Sic
-- Subject: Unit sickrage.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit sickrage.service has failed.

**Comment by dannyti** [comment]
Try this : 

systemctl start sickrage.service (starts sickrage)
systemctl stop sickrage.service (stops sickrage)
systemctl restart sickrage.service (restarts sickrage if it was already running; starts it if it was not)
systemctl status sickrage.service (gives some status info on sickrage if it is running, or what happened the last time it was run)

**Comment by Switouney** [comment]
hello, thx for fast reply

root@sd-88161:~# systemctl start sickrage.service
Job for sickrage.service failed. See 'systemctl status sickrage.service' and 'journalctl -xn' for details.
root@sd-88161:~# systemctl stop sickrage.service
root@sd-88161:~# systemctl restart sickrage.service
Job for sickrage.service failed. See 'systemctl status sickrage.service' and 'journalctl -xn' for details.
root@sd-88161:~# systemctl status sickrage.service
● sickrage.service - LSB: starts instance of SickBeard
   Loaded: loaded (/etc/init.d/sickrage)
   Active: failed (Result: exit-code) since Tue 2016-01-05 02:08:26 CET; 5s ago
  Process: 14675 ExecStart=/etc/init.d/sickrage start (code=exited, status=1/FAILURE)

Jan 05 02:08:26 sd-88161 sickrage[14675]: Starting SickBeard:PID file: /var/....
Jan 05 02:08:26 sd-88161 sickrage[14675]: failed!
Jan 05 02:08:26 sd-88161 systemd[1]: sickrage.service: control process exit...=1
Jan 05 02:08:26 sd-88161 systemd[1]: Failed to start LSB: starts instance o...d.
Jan 05 02:08:26 sd-88161 systemd[1]: Unit sickrage.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.
root@sd-88161:~#

**Comment by dannyti** [comment]
What's your OS ?

**Comment by Switouney** [comment]
Debian 8, i can give my teamviewer if u want see... ;)

**Comment by dannyti** [comment]
What's your OS ?

**Comment by Switouney** [comment]
my os is debian 8. do you have jabber/ instant messaging?

**Comment by dannyti** [comment]
Install remove & purge sickragetv and install as main user. 

If it still doesn't works ; follow the following steps:

sudo chown -R user:user /opt/sickrage

python /opt/sickrage/SickBeard.py -d

**Comment by Switouney** [comment]
it's ok, thanks
