### ISSUE TITLE
MediaStream not working

### ISSUE THREAD

**Issue by cytec** [dannyti/sboxsetup#13]
seems like the Streaming plugin isn't working correctly.

I get an error in VLC that the source could not be played.
When i open the URL in the browser i just get a blank white page

**Comment by dannyti** [comment]
I understand the file is unrared and media player is having the required codecs.

Have you tried any other media player or the default divx player via web browser ? Is that working ?


You can try the fix for vlc:

https://code.google.com/p/rutorrent-stream-plugin/source/browse/wiki/HowTo.wiki?r=4

**Comment by cytec** [comment]
Thanks for your answer. when i click stream in rutorrent i get a file downloaded containing a stream url like this:

```http://SERVERIP/rutorrent/plugins/stream/stream.php?f=%252Fpath%252Fto%252Fmedia.mkv```

When i try to open that file in VLC i get a promt asking for user/pass if i enter both i get an error that the media can not be found. If i change config.php to include my user:pass it just doesn't do anything.

Disableing SSL doesn't help.

But when i then open the URL in the browser it "downloads" a 0Byte media.mkv file.

**Comment by cytec** [comment]
also i'm gettin a lot of this in error logs:

```
[Tue Jan 05 10:35:54.041457 2016] [auth_digest:error] [pid 1672] [client xxxx] AH01788: realm mismatch - got `documentroot' but expected `rutorrent', referer: https://xxxxx/rutorrent/
```

**Comment by cytec** [comment]
Nevermind... i just figured out that xsendfile was enabled, after disableing it everything works as it should. Sorry!
