### ISSUE TITLE
Fail2ban not starting on new install

### ISSUE THREAD

**Issue by DetectiveStern** [dannyti/sboxsetup#14]
On a fresh install of ubuntu server 15.04 64bit, the script completed successfully however I found that fail2ban is failing to start. It could be an OS issue and not the script but I wanted to report it regardless.

● fail2ban.service - Fail2Ban Service
   Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset: enabled                                                      )
   Active: failed (Result: start-limit) since Fri 2016-01-08 23:00:20 EST; 22s ago
     Docs: man:fail2ban(1)
  Process: 1049 ExecStart=/usr/bin/fail2ban-client -x start (code=exited, status=1/FAILU                                                      RE)

Jan 08 23:00:20 vps systemd[1]: Failed to start Fail2Ban Service.
Jan 08 23:00:20 vps systemd[1]: Unit fail2ban.service entered failed state.
Jan 08 23:00:20 vps systemd[1]: fail2ban.service failed.
Jan 08 23:00:20 vps systemd[1]: fail2ban.service holdoff time over, scheduling restart.
Jan 08 23:00:20 vps systemd[1]: start request repeated too quickly for fail2ban.service
Jan 08 23:00:20 vps systemd[1]: Failed to start Fail2Ban Service.
Jan 08 23:00:20 vps systemd[1]: Unit fail2ban.service entered failed state.
Jan 08 23:00:20 vps systemd[1]: fail2ban.service failed.

**Comment by dannyti** [comment]
Try,
systemctl enable fail2ban

**Comment by dannyti** [comment]
Change to original file and will start the fail2ban service.
cd /etc/fail2ban/
sudo mv jail.conf jail.conf.bak
sudo mv jail.conf.original jail.conf
service fail2ban start

**Comment by DetectiveStern** [comment]
Thanks for the help, I tried the above and a combination of other things but I think what fixed it was the creation of jail.local.
