### ISSUE TITLE
Custom work

### ISSUE THREAD

**Issue by ADz-83** [dannyti/sboxsetup#15]
Hi Danny,

I was wondering if you would be able to work on a customized script for me based on the one you currently maintain? I would pay you for your time.

I'm looking to privately host standalone script myself once tweaked and not rely on external sources. Basically just want some default values set in users boxes created like plugins/no DHT etc as well as some controls removed from WebUI. Also access to FTP would be limited to download and watch folder only, no access to .rc file or other users etc.

Would you be able to help with this?

Kind regards,
Andrew

**Comment by dannyti** [comment]
This is for script issues.
Find me in ti forums.

**Comment by ADz-83** [comment]
I did but it would not let me PM you Danny,  user group restrictions.   Could you contact me on illyayevdokymov@gmail.com then remove this post,  thanks  :)

**Comment by ADz-83** [comment]
Looks like your hushmail email expired Dan so can't reply to your email.  It won't let me pm on TI either.

Could you please you email me illyaYevdokymov ..at.. gmail.com
