### ISSUE TITLE
Users have access to each others files even if not a sudo user.

### ISSUE THREAD

**Issue by systemuser1** [dannyti/sboxsetup#17]
I created a normal user with no sudo rights. Everything works well. When the user logs in from FileZilla with port 21201 (FTP Port) it works well. But when the same user logs in with port 21976 (SSH/SFTP Port) he gets access to every directory including every users.
It seems a very crucial issue, hope it gets fixed soon.

Thank You.

**Comment by dannyti** [comment]
It's not an issue per se but never planned. You can try to make home directories only readable by owner but it will screw everything as rutorrent folder is common for all in /var/www/rutorrent/ unlike commercial seedboxers who have individual rutorrent folder within the user's home folder.

**Comment by dannyti** [comment]
Closing for now as not possible with present script.
Later, if you know how to do this, open this Issue.
