### ISSUE TITLE
installSUBSONIC

### ISSUE THREAD

**Issue by shark-oxi** [dannyti/sboxsetup#19]
Hi

From `installSUBSONIC` script : 
change `http://subsonic.org/download/subsonic-5.2.1.deb` to `http://subsonic.org/download/subsonic-6.0.deb`because 5.2.1 is no more available on subsonic servers.

Thanks

**Comment by dannyti** [comment]
Done. Thanks.

**Comment by shark-oxi** [comment]
I'm curious but I didn't see where is the installSUBSONIC and others scripts you add to [seedbox-from-scratch](https://github.com/Notos/seedbox-from-scratch), because there nor on your repo nor on Notos repo ?
