### ISSUE TITLE
Add installEMBY

### ISSUE THREAD

**Issue by shark-oxi** [dannyti/sboxsetup#20]
As a great Plex or Subsonic alternative there is [Emby](http://emby.media/index.html).
It's like Plex, good as Plex but it's open source :)

Here the script for Debian 8 : 
```bash
#!/bin/bash
MAINUSER1=`cat /etc/seedbox-from-scratch/mainuser.info`
IPADDRESS1=`cat /etc/seedbox-from-scratch/hostname.info`
logfile="/dev/null"
echo "Installing Emby . . . . "
#Emby
echo 'deb http://download.opensuse.org/repositories/home:/emby/Debian_8.0/ /' >> /etc/apt/sources.list.d/emby-server.list 
apt-get update
apt-get install emby-server
sudo service emby-server start
echo ""
echo ""
echo "Emby is installed."
echo "Access Emby on http://$IPADDRESS1:8096 "
echo "Run the Startup Wizard ASAP"
echo "You can get help on https://github.com/MediaBrowser/Wiki/wiki/Installation"
echo ""
```

**Comment by shark-oxi** [comment]
Here the script for Ubuntu 15.10 : 
```bash
#!/bin/bash
MAINUSER1=`cat /etc/seedbox-from-scratch/mainuser.info`
IPADDRESS1=`cat /etc/seedbox-from-scratch/hostname.info`
logfile="/dev/null"
echo "Installing Emby . . . . "
#Emby
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/emby/xUbuntu_15.10/ /' >> /etc/apt/sources.list.d/emby-server.list"
sudo apt-get update
sudo apt-get install emby-server
sudo service emby-server start
echo ""
echo ""
echo "Emby is installed."
echo "Access Emby on http://$IPADDRESS1:8096 "
echo "Run the Startup Wizard ASAP"
echo "You can get help on https://github.com/MediaBrowser/Wiki/wiki/Installation"
echo ""
```

**Comment by shark-oxi** [comment]
SOrry, I forget to add `-q -y` options to `apt-get install` in order to make it non-interactive.

**Comment by shark-oxi** [comment]
Here the script for Ubuntu 15.04 : 
```bash
#!/bin/bash
MAINUSER1=`cat /etc/seedbox-from-scratch/mainuser.info`
IPADDRESS1=`cat /etc/seedbox-from-scratch/hostname.info`
logfile="/dev/null"
echo "Installing Emby . . . . "
#Emby
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/emby/xUbuntu_15.04/ /' >> /etc/apt/sources.list.d/emby-server.list"
sudo apt-get update
sudo apt-get install emby-server
sudo service emby-server start
echo ""
echo ""
echo "Emby is installed."
echo "Access Emby on http://$IPADDRESS1:8096 "
echo "Run the Startup Wizard ASAP"
echo "You can get help on https://github.com/MediaBrowser/Wiki/wiki/Installation"
echo ""
```

**Comment by shark-oxi** [comment]
You can get more help on : 
[Emby server for linux page](http://emby.media/linux-server.html)
and
[Emby package documentation page of openSUSE](https://software.opensuse.org/download.html?project=home%3Aemby&package=emby-server)

**Comment by shark-oxi** [comment]
@dannyti did you add it ?

**Comment by dannyti** [comment]
No, no plans to add this.

**Comment by shark-oxi** [comment]
But I gave you all the scripts ... you have barely nothing to do

**Comment by shark-oxi** [comment]
If you support Plex and Subsonic, why not Emby too ?

**Comment by dannyti** [comment]
I don't see any advantage Emby has over Plex. As for use, Plex is more popular and gets the things done. Adding this will require some time to test it which I don't have for now. 

If there is more interest in this Or if I find it more easy and better than Plex, I will look into this. Thanks for the scripts but this will have to wait.

**Comment by shark-oxi** [comment]
Emby advantages over Plex are : open source, easier database management, more flexible and customizable, better live tv / pvr support.
Only disadvantages of Emby are due to his young age, but while it's becoming to be established, Emby will have only advantages over Plex.

You can see differences [here](http://www.htpcbeginner.com/plex-vs-emby-comparison-with-kodi/).

I installed Emby on my VPS, it's pretty easy to install and it has a Plex-like interface.

From my point of view (and that's only my point of view) Emby is Plex in better and open source.

I understand you have no time. Thanks for sboxsetup.
