### ISSUE TITLE
Any chance of adding Rapidleech MTN script.

### ISSUE THREAD

**Issue by systemuser1** [dannyti/sboxsetup#21]
Rapidleech is installed by default in this script. 
By any chance you could implement the Rapidleech Movie Thumbnailer into this script. I have seen it installed on many seedbox providers. Its function is to generate screenshots and also Thumbnail Sheet of a video file.
I just did a few google searches, from my knowledge I think it needs a mtn.php file to be placed in /rapidleech/mtn.php

This script is amazing anyways. Thank You..!!

**Comment by dannyti** [comment]
No.
