### ISSUE TITLE
grsecurity may cause visibility issues

### ISSUE THREAD

**Issue by shinji257** [dannyti/sboxsetup#3]
grsecurity has an isolation patch that prevents non-root users from seeing other users processes.  Unless ps is run with sudo access it won't see the needed processes to kill when running deleteSeedboxUser.  As a consequence the script can't delete the target user either (it is locked due to the still active screen sessions).  Simply running the ps command with sudo during the kill line should be enough to get around this issue.

sudo kill -9 $( sudo ps -ef | grep $NEWUSER1 | awk '{ print $2 }' )

**Comment by dannyti** [comment]
Noted & added to script.
Thanks.

**Comment by shinji257** [comment]
Your welcome. ;)
