### ISSUE TITLE
installPLEX failing due to installation files missing from Plex servers

### ISSUE THREAD

**Issue by maciebey** [dannyti/sboxsetup#36]
Raising an issue for installPLEX script failing. Don't see it in the repo, assuming it's downloaded during install. Appears like Plex moved the referenced v1.0.2 file from their servers.

Current workaround for anyone wondering, modify the install script with 

`sudo nano /etc/seedbox-from-scratch/installPLEX`

Replace the url in the first in block with https://downloads.plex.tv/plex-media-server/1.9.7.4460-a39b25852/plexmediaserver_1.9.7.4460-a39b25852_amd64.deb and change the references to the deb file on the following line and on the last line of the block.

Do the same with the second block with https://downloads.plex.tv/plex-media-server/1.9.7.4460-a39b25852/plexmediaserver_1.9.7.4460-a39b25852_i386.deb .

On my Ubuntu 16_04 release my file looks like this after changes, installed and have Plex working fine

```
#!/bin/bash
IPADDRESS1=`cat /etc/seedbox-from-scratch/hostname.info`
logfile="/dev/null"
OS1=$(lsb_release -si)
echo "Installing Plex Media Server . . . ."
if [ `getconf LONG_BIT` = "64" ]; then
  wget -c https://downloads.plex.tv/plex-media-server/1.9.7.4460-a39b25852/plexmediaserver_1.9.7.4460-a39b25852_amd64.deb >> $logfile 2>&1
  sudo dpkg -i plexmediaserver_1.9.7.4460-a39b25852_amd64.deb >> $logfile 2>&1
  sudo apt-get install -f >> $logfile 2>&1
  rm plexmediaserver_1.9.7.4460-a39b25852_amd64.deb
else
  wget -c https://downloads.plex.tv/plex-media-server/1.9.7.4460-a39b25852/plexmediaserver_1.9.7.4460-a39b25852_i386.deb >> $logfile 2>&1
  sudo dpkg -i plexmediaserver_1.9.7.4460-a39b25852_i386.deb >> $logfile 2>&1
  sudo apt-get install -f >> $logfile 2>&1
  rm plexmediaserver_1.9.7.4460-a39b25852_i386.deb
fi

echo ""
echo "Plex Media Server is installed"
echo ""
echo "To enable remote access, set up ssh tunnel;"
echo "and access - http://$IPADDRESS1:32400/web"
echo "For initial Plex Setup check : "
echo "https://github.com/dannyti/sboxsetup/wiki/Initial-set-up-of-Plex-Media-Server"
echo ""
```

**Comment by dannyti** [comment]
Updated. 

Cheers.
