### ISSUE TITLE
Bug?: Deluge Daemon isn't accessible after setup

### ISSUE THREAD

**Issue by shinji257** [dannyti/sboxsetup#5]
I suspect that this also affects newly created users as well but I didn't test.  After setting up the script I found that I couldn't connect to the Deluge Daemon via the port specified in the SBInfo.  When checking the auth file I found that only the local account was present.  There was no auth entry for remote access.  I added one then restarted services after which everything was good.  Thought to let you know.  Might need to tweak a few of the scripts if you wanted the daemon access to use the same password as everywhere else.

**Comment by dannyti** [comment]
Can you specify which auth entry for remote web access ?

**Comment by shinji257** [comment]
The individual user account is missing in the deluge auth file.  I suspect the entry is being added too early and deluge is overwriting it when it finds the localclient login that it generates isn't present since when I checked it that was the only login that was present.  I still had to append my own login after that.  Keep in mind that while I'm reporting this here I realize this is an upstream issue from the repo you forked.
