### ISSUE TITLE
Install Command

### ISSUE THREAD

**Issue by TheoNorep** [dannyti/sboxsetup#7]
Hello all and dannyti ! 

Firstly ! Thank you so much for this script ! 

But, i can't find the install command on the Wiki... ? What's the install command to install it on my dedicated server ? 

Thanks you in advance !

Sorry for my bad english, i'm french . 

--
Théo Norép

**Comment by OoGuru** [comment]
Here it is:
Step one - downloading the bash file:
wget https://github.com/dannyti/sboxsetup/raw/master/sbfrmsc-dti.sh

Step two - starting the installation in the folder where you downloaded the bash file
bash sbfrmsc-dti.sh

Step three - follow the instructions; remember the username must not have any capital letters in it. Use lowercase!

Step four - wait till it is done installing and has completed the restart

Step five - login using your user account

I hope this will help you :)

**Comment by TheoNorep** [comment]
Hello OoGuru !

Big Thanks ! :)

This script is wonderful !

Thanks again ! 
--
Theo Norep

**Comment by tomyam555** [comment]
Hi there. thanks alot!!! its working fine with my vps but i am having problem getting Plex to work. After installed and signed in to http://Your-WebServer-IP:32400/web Plex can't find the server. Please advise and thanks again
