### ISSUE TITLE
Torrents client acts as new user, Sickrage acts and root

### ISSUE THREAD

**Issue by kerbysj** [dannyti/sboxsetup#8]
Wounderful script however i have a slight permitions problem.

after testing the script everything is working however Sickrage is running as root not the user i installed as.

Also rutorrent autotools has a slow pickuprate and also the download folder for rtorrent reverts after reboot.
Can i change the upstart for sickrage to run as a user?
Where is rtorrent config files saved
where is rutorrent files saved?

**Comment by dannyti** [comment]
Sick rage runs as root and I do not know about running it as a user. A Google search might help you there. 

The settings via rutorrent interface are not permanent they are temporary. This is from the maintainer of rutorrent. If you want permanent changes then stop rtorrent and edit /home/USER/.rtorrent.rc file. The start rtorrent. 

Watch folders from irssi pick up torrent quickly. 

rutorrent files: /var/www/rutorrent
